# Site settings
title: Spectral
email: your-email@domain.com
description: Another fine responsive site template
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Customize the content by editing index.html
# Update social media links, email, and contact information as needed

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
